branches:
  except:
    - /^legacy\/.*$/
    - heroku
language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
env:
  global:
    - APP_ENV='testing'
  matrix:
    - "DB=pgsql"
    - "DB=mysql"
matrix:
  exclude:
    - php: hhvm
      env: DB=pgsql  # driver for PostgreSQL currently unsupported by HHVM, requires 3rd party dependency
  allow_failures:
    - php: 7.0
sudo: false
before_install:
  - hostname
  - composer self-update
install: travis_retry composer install --prefer-source --no-interaction
before_script:
  - php artisan env
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS solder;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database solder;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS solder;'; fi"
  - php artisan migrate:install
  - php artisan migrate
  - php artisan db:seed --class="TestSeeder"
script: vendor/bin/phpunit --verbose
